# Generated by jaraco.develop (https://bitbucket.org/jaraco/jaraco.develop)
import setuptools

with open('README') as f:
	long_description = f.read()

setup_params = dict(
	name='cython-plugin',
	version="1.0",
	author="Jason R. Coombs",
	author_email="jaraco@jaraco.com",
	description="Setuptools plugin for Cython",
	long_description = long_description,
	url="https://bitbucket.org/jaraco/cython-plugin",
	py_modules = ['cython_loader'],
	entry_points = {
		'distutils.setup_keywords': [
			'use_cython = cython_loader:set_build_ext'
		],
	},
	install_requires = ['cython'],
)

if __name__ == '__main__':
	setuptools.setup(**setup_params)
